### PR TITLE
Multiple improvements

### PR DESCRIPTION
**Pull request by lsmoura**
- Fix version number.
- Added multi-threading support.
- Added redis cache support.
- Support for `.env` file.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Any update to buildLang for multithread?

**Comment by lsmoura** [comment]
I can do the buildLang too.

**Comment by tooomm** [comment]
This fixes #530

**Comment by ZeldaZach** [comment]
Any updates on this PR @lsmoura

**Comment by tooomm** [comment]
Any improvements or progress in between @lsmoura?

**Comment by ZeldaZach** [comment]
Closing as no further advancements made and we're moving to v4 soon, so no more need for major code changes here

**Pull request closed without merging**
